"""upgrade nas tabelas

Revision ID: b01c2d624886
Revises: f19f73b36523
Create Date: 2025-10-23 23:40:24.454733+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01c2d624886'
down_revision: Union[str, None] = 'f19f73b36523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('debts_companies_id_fkey'), 'debts', type_='foreignkey')
    op.create_foreign_key(None, 'debts', 'companies', ['company_id'], ['id'])
    op.drop_column('debts', 'companies_id')
    op.alter_column('transactions', 'debt_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'payment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'payment_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('transactions', 'debt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('debts', sa.Column('companies_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.create_foreign_key(op.f('debts_companies_id_fkey'), 'debts', 'companies', ['companies_id'], ['id'])
    op.drop_column('debts', 'company_id')
    # ### end Alembic commands ###
