"""new debt table version

Revision ID: ac4c353e218b
Revises: 5f40125a0f5b
Create Date: 2025-11-08 15:43:36.668301+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4c353e218b'
down_revision: Union[str, None] = '5f40125a0f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('debtor_name', sa.String(length=255), nullable=False))
    op.add_column('debts', sa.Column('debtor_contact', sa.String(length=255), nullable=False))
    op.add_column('debts', sa.Column('debtor_cpf', sa.String(length=14), nullable=False))
    op.drop_constraint(op.f('debts_debtor_id_fkey'), 'debts', type_='foreignkey')
    op.drop_column('debts', 'debtor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('debtor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('debts_debtor_id_fkey'), 'debts', 'debtors', ['debtor_id'], ['id'])
    op.drop_column('debts', 'debtor_cpf')
    op.drop_column('debts', 'debtor_contact')
    op.drop_column('debts', 'debtor_name')
    # ### end Alembic commands ###
