"""add CPF column in debtors table

Revision ID: 18979853bce4
Revises: b01c2d624886
Create Date: 2025-11-06 00:48:28.307257+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18979853bce4'
down_revision: Union[str, None] = 'b01c2d624886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtors', sa.Column('debtor_cpf', sa.String(length=14), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debtors', 'debtor_cpf')
    # ### end Alembic commands ###
